# Programming for Data Analysis 2021 - Assignment

## 1. Explain the overall purpose of the numpy.random package.

NumPy (short for Numerical Python) is a Python library which is used for dealing with arrays of numerical values. 
Arrays can be 0-, 1- or multi-dimensional (matrices). 
All elements of an array need to be of the same data type. 

To be able to use it, needs to be imported. It is commonly imported as np. 

In [1]:
import numpy as np

numpy.random is a module within the NumPy library enabling users to generate and work with random numbers.
Pseudo-random numbers: generated through a generation algorithm which is not truly random.
Truly random numbers can be generated using random data from an outside source which could be mouse movements, time stamps, etc. 



In [2]:
# To be able to use the random module, it needs to be imported:
from numpy import random
x = random.rand()
x

0.5693784002033353

BitGenerators - Create sequences of random numbers
Generators - use the created sequences to sample from different statistical distributions

In [3]:
# rng = random number generator
from numpy.random import default_rng
rng = default_rng()
# Return 20 random integers from 0 to 10 (exclusive)
vals = rng.integers(10, size=20)
vals

array([2, 9, 3, 6, 6, 7, 1, 0, 5, 6, 4, 8, 8, 2, 1, 8, 5, 2, 0, 4],
      dtype=int64)

In [4]:
# Return random float point number between 0.0 and 1.0
rng = np.random.default_rng()
rng.random(size=10)

array([0.45921558, 0.49264247, 0.03123534, 0.02662885, 0.07290101,
       0.26467423, 0.67105071, 0.70524751, 0.99219408, 0.15352284])

In [5]:
np.random.default_rng().bytes(10)

b'\xb5C\x81\xda%\xa3\xf2i\x9d\xef'

References:

https://www.w3schools.com/python/numpy/numpy_random.asp (30/10/2021)

Numpy v.1.21 Manual https://numpy.org/doc/stable/ (30/10/2021)

Random sampling (numpy.random) https://numpy.org/doc/stable/reference/random/index.html# (30/10/2021)

## 2. Explain the use of the “Simple random data” and “Permutations” functions.

Permutations: https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.permutation.html

Simple random data: Return integers, floats, a random sample from a given array or bytes
<br>
Permutations: Modifies an array or sequence already in place by shuffling or permuting the sequence

### **2.1 Simple Random Data**
A number of functions can be used to generate simple random data, for example single or several numbers.

#### **2.1.1 Generating Random Integers**
Using the rng.integers() function to create random integers. 

In [10]:
# To create random integers: 
# rng = random number generator
from numpy.random import default_rng
rng = default_rng()

# To return 1 random integer from 0 to 5 (exclusive)
vals = rng.integers(5)
vals

4

The rng.integers() function can take a number of parameters to define
- The range from which integers can be drawn (low, high)
- The number of random integers to be drawn (size)
- Data type of results
- Endpoint = True sets the high value to be inclusive of the entered value

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html (13/11/2021)



In [26]:
# Example: Generate an array of 5 integers between 10 (inclusive) and 20 (exclusive)
rng = np.random.default_rng()
rng.integers(10, 20, 5)

array([19, 13, 15, 15, 16], dtype=int64)

#### **2.1.2 Generating Random Float Numbers**

The rng.random() function can be used to create float point numbers between 0 and 1 (exclusive).


In [24]:
# Exapmle: Creating a float point number
fnumber = rng.random()
fnumber

0.12533751747499688

Similar to creating integers, additional parameters canbe added to further define the output: 
- The number of random float numbers to be drawn (size)
- Data type (float64 or float32)
- An alternative output array

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.random.html#numpy.random.Generator.random (13/11/2021)

In [25]:
# Example for creating an array of 5 float point numbers
fnumbers = rng.random(5)
fnumbers

array([0.20094955, 0.09716152, 0.85312873, 0.48581303, 0.39000584])

#### **2.1.3 Generating n-dimensional Arrays of Random Numbers**

Both rng.integers() and rng.random() can be used to create n-dimensional arrays of random numbers. 

--> need more details and example


#### **2.1.4 Selecting Random Numbers from a Predefined Array**

The rng.choice() function can be used to generate a random sample from a given array. 

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.choice.html#numpy.random.Generator.choice (13/11/2021)

In [31]:
# Example: Select 3 integers from an array of [1, 2, 3, 4, 5]
rng.choice([1,2,3,4,5], 3)

array([3, 1, 2])

An important aspect of random number generation is the distribution of data. The rng.choice() function can be used to define the probability of random numbers being selected by assigning probability values. 

In [33]:
# Example: Select 10 integers from an array of [1, 2, 3, 4, 5]. The probability of selecting 1, 2 and 3 is set to 0.3, 
# the probaility of selecting 4 is set to 0.1 and the probablility of selecting 5 is set to 0:

ch = rng.choice([1,2,3,4,5], 10, p=(0.3, 0.3, 0.3, 0.1, 0))
ch

array([2, 3, 1, 1, 1, 3, 2, 1, 2, 4])

### **2.2 Permutations**

Random permuations can be used to re-arrange elements within a given array, for example by changing the order of [1, 2, 3] to [3, 2, 1].
The numpy.random package offers 3 methods for changing the order of array elements: 
- shuffle()
- permutation()
- permuted()

#### **2.2.1 Re-shuffling an Array**
The shuffle() function changes the original array by re-arranging its elements. 

https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.shuffle.html#numpy.random.Generator.shuffle (13/11/2021)

In [35]:
# Example: 
arr = [1,2,3,4,5]

rng.shuffle(arr)
arr

[2, 4, 3, 1, 5]

## 3. Explain the use and purpose of at least five “Distributions” functions.

## 4. Explain the use of seeds in generating pseudorandom numbers.

## References Used